# Generated by Django 2.1.5 on 2019-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgURL',
            field=models.CharField(default='please input', max_length=300),
            preserve_default=False,
        ),
    ]
